export const ERROR_CODE = {
  NO_TOKEN: "NO_TOKEN",
  INVALID_TOKEN: "INVALID_TOKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  GAME_NOT_FOUND: "GAME_NOT_FOUND",
  GAME_CREATE_FAILED: "GAME_CREATE_FAILED",
  GAME_JOIN_FAILED: "GAME_JOIN_FAILED",
  GAME_ALREADY_IN_PROGRESS: "GAME_ALREADY_IN_PROGRESS",
  GAME_NOT_IN_PROGRESS: "GAME_NOT_IN_PROGRESS",
  ALREADY_JOINED: "ALREADY_JOINED",
  NOT_YOUR_TURN: "NOT_YOUR_TURN",
  NO_ROLLS_LEFT: "NO_ROLLS_LEFT",
  NOTHING_TO_KEEP: "NOTHING_TO_KEEP",
  NOT_ROLLED: "NOT_ROLLED",
  INVALID_SCORE: "INVALID_SCORE",
  CATEGORY_TAKEN: "CATEGORY_TAKEN",
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
